apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flectra-data
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
