apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flectra-addons
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
